### PR TITLE
Updated to React Native 0.5 and solved resizeMode warning

### PR DESCRIPTION
**Pull request by alvaromb**
This is a minor update, just updated to React Native 0.5 and solved resizeMode warning.

### CODE REVIEW

**Comment by mosch** [comment]
:+1:

**Comment by cyprusglobe** [comment]
we need to also get react-native-blur updated.

**Comment by alvaromb** [comment]
@cyprusglobe yes it's true. I'll work on this this evening. They release `react-native` every two weeks or so, it's hard to keep everything updated.

**Comment by cyprusglobe** [comment]
@alvaromb looks like react-native-blur is updated

**Comment by lelandrichardson** [comment]
thanks for this! finally getting some time to tend to this project (sorry everyone!)

**Comment by alvaromb** [comment]
That's cool @lelandrichardson! I'm also struggling to find some time to maintain and develop a couple of react-native apps, some of them are already in the AppStore. I would love to help if you need something, let's hope I can find an empty slot to work on this stuff. We're busy developers, aren't we?  :shipit:

**Pull request merged**
