### PR TITLE
Compatibility fix for RN 0.26

### PR DESCRIPTION
**Pull request by aprct**
Resolves issue #31

### CODE REVIEW

**Comment by aprct** [comment]
@charliesbox You can do this in the mean time:
In your package.json require this under your dependencies 
`"react-native-parallax-view": "aprct/react-native-parallax-view#upgrade-to-rn-0.26",` 
(as opposed to `"react-native-parallax-view": "latest"`, for example).

👍

**Comment by dozoisch** [comment]
@lelandrichardson Is it possible to merge this!

**Comment by dozoisch** [comment]
@lelandrichardson Thank you :)

**Comment by lelandrichardson** [comment]
merged and published as v2.0.5

Sorry for the wait!

**Pull request merged**
